homepage:
    path:     /
    defaults: { _controller: AppBundle:Task:list }

task.new:
    path:     /task/new
    defaults: { _controller: AppBundle:Task:edit }

task.edit:
    path:     /task/edit/{id}
    defaults: { _controller: AppBundle:Task:edit }
    requirements:
        id: '\d+'
